// Dummy patient data — replace with API later
const patients = [
  {
    id: 1,
    name: "Meena Devi",
    score: 82,
    level: "HIGH",
    reason: "Missed follow-up + diabetes",
    age: 47,
    village: "Rampur",
    lastVisit: "12 Apr 2025",
    phone: "98XXXXXX01",
    conditions: ["Type 2 Diabetes", "Hypertension"],
    visited: false,
  },
  {
    id: 2,
    name: "Ravi Kumar",
    score: 60,
    level: "MEDIUM",
    reason: "Recent discharge + age 55+",
    age: 58,
    village: "Sundarpur",
    lastVisit: "28 Apr 2025",
    phone: "99XXXXXX12",
    conditions: ["Post-surgery recovery"],
    visited: false,
  },
  {
    id: 3,
    name: "Lakshmi Bai",
    score: 30,
    level: "LOW",
    reason: "Stable condition",
    age: 34,
    village: "Nayagaon",
    lastVisit: "01 May 2025",
    phone: "97XXXXXX34",
    conditions: ["Routine check"],
    visited: false,
  },
  {
    id: 4,
    name: "Sunita Yadav",
    score: 75,
    level: "HIGH",
    reason: "Anaemia symptoms + pregnant",
    age: 24,
    village: "Baishpur",
    lastVisit: "15 Apr 2025",
    phone: "96XXXXXX56",
    conditions: ["Anaemia (suspected)", "Pregnancy – 7 mo."],
    visited: false,
  },
  {
    id: 5,
    name: "Gopal Singh",
    score: 45,
    level: "MEDIUM",
    reason: "TB medication compliance",
    age: 62,
    village: "Rampur",
    lastVisit: "25 Apr 2025",
    phone: "94XXXXXX78",
    conditions: ["Tuberculosis (treatment)"],
    visited: false,
  },
];

export default patients;