const patients = [
  {
    id: 1,
    name: "Meena Bai",
    age: 28,
    village: "Wardha",
    diagnosis: "Dengue + Diabetes",
    dischargeDays: 8,
    riskScore: 82,
    riskLevel: "HIGH",
    medication: false,
    lastVisit: null,
    asha: "Sunita Devi",
    anemia: null,
    reason: "8 days post-discharge, diabetic, missed medication",
    status: "Pending follow-up",
  },
  {
    id: 2,
    name: "Radha Patil",
    age: 45,
    village: "Seloo",
    diagnosis: "Hypertension",
    dischargeDays: 3,
    riskScore: 61,
    riskLevel: "MEDIUM",
    medication: true,
    lastVisit: "2 days ago",
    asha: "Sunita Devi",
    anemia: "Mild",
    reason: "3 days post-discharge, blood pressure monitoring",
    status: "Monitoring",
  },
  {
    id: 3,
    name: "Kaveri Nair",
    age: 32,
    village: "Arvi",
    diagnosis: "Post-natal",
    dischargeDays: 5,
    riskScore: 74,
    riskLevel: "HIGH",
    medication: false,
    lastVisit: null,
    asha: "Sunita Devi",
    anemia: null,
    reason: "5 days post-discharge, post-natal, missed medication",
    status: "Pending follow-up",
  },
  {
    id: 4,
    name: "Sushma Gaikwad",
    age: 55,
    village: "Wardha",
    diagnosis: "TB",
    dischargeDays: 12,
    riskScore: 45,
    riskLevel: "MEDIUM",
    medication: true,
    lastVisit: "yesterday",
    asha: "Sunita Devi",
    anemia: "Normal",
    reason: "12 days post-discharge, TB medication on track",
    status: "Active",
  },
  {
    id: 5,
    name: "Anita Kolekar",
    age: 22,
    village: "Hinganghat",
    diagnosis: "Anemia",
    dischargeDays: 1,
    riskScore: 30,
    riskLevel: "LOW",
    medication: true,
    lastVisit: "today",
    asha: "Sunita Devi",
    anemia: "Mild",
    reason: "1 day post-discharge, anemia follow-up",
    status: "Visited",
  },
];

export default patients;
